### ISSUE TITLE
Blu ray player play/pause status not working, control works and Netflix works

### ISSUE THREAD

**Issue by dshokouhi** [tuxuser/home-assistant-xboxone#1]
After setting up the server and authenticating the custom component loads fine.  When I go in Netflix I can see the app updating properly with the playing status, very quickly might I add.

![image](https://user-images.githubusercontent.com/1634145/43811054-9a3b04b4-9a6f-11e8-9633-7f712408d8d9.png)

When I go to the bluray player I see the app load but playing status never changes, the app is detected and controls work fine:

![image](https://user-images.githubusercontent.com/1634145/43811073-ae5dfa28-9a6f-11e8-80e7-9a00e5729461.png)

**Comment by tuxuser** [comment]
**Cause of the behaviour**
(Long) MediaState messages make use of the `fragment` flag in the MessageHeader.
Previously this flag was ignored and a fragmented Message was just parsed as their underlying type.

It should have been parsed as `MessageFragment` first, then the assembled payload parsed as `MediaStateMessage`

**Fixed**
OpenXbox/xbox-smartglass-core-python@1b264b4bac0fa90a21dc8e4af7844ab41290745b **Extend FragmentManager to handle MessageFragments**
OpenXbox/xbox-smartglass-core-python@9a57926cc5b4dde66418c8f8f8c674ed736186f4 **Support parsing MessageFragment packets, adding tests**

Waiting for your test results ;)

**Comment by tuxuser** [comment]
Verified working
[CLOSED]
